# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

indicator_array <- function(z, C) {
    .Call(`_mrf2dbayes_indicator_array`, z, C)
}

inner_gibbs_conditional <- function(zinit, cond_weights, R, theta, ncycles = 1L) {
    .Call(`_mrf2dbayes_inner_gibbs_conditional`, zinit, cond_weights, R, theta, ncycles)
}

